######## Build
FROM rust:1.86-alpine AS build-env
RUN apk add --no-cache musl-dev
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY ./src ./src
RUN cargo build --release && \
    cp /app/target/release/rurl-shortener /app/rurl-shortener

######## Run
FROM rust:1.86-alpine
COPY --from=build-env /app/rurl-shortener /
ENTRYPOINT ["/rurl-shortener"]
