openapi: 3.0.0

info:
  title: OpenAPI specification of rurl shortener
  version: 0.1.0
servers:
  - url: http://localhost:4444
    description: Backend

paths:
  /status:
    get:
      summary: Status of the server
      operationId: getStatus
      tags:
        - RURL Shortener
      responses:
        '200':
          description: "Server is healthy"
  /api/v1/{short}:
    get:
      summary: Redirect to original link
      operationId: getUrl
      tags:
        - RURL Shortener
      responses:
        '301':
          description: Moved Permanently
          headers:
            Location:
              schema:
                type: string
              example: "https://en.wikipedia.org/wiki/Wikipedia"
              description: "Original full link"
        '404':
          description: Not Found
      parameters:
        - name: "short"
          in: path
          description: "Get the link that's shorten by this"
          required: true
          schema:
            type: string
            format: path
  /api/v1/:
    post:
      summary: Create short link
      requestBody:
          required: true
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ShortenRequest"
      responses:
        '200':
          description: "Successfully shorten"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/ShortenResponse"
        '503':
          description: "Cannot generate unique short link"
        '400':
          description: "Bad request"

components:
  schemas:
    ShortenRequest:
      type: object
      required:
        - url
      properties:
        url:
          description: Link to be shortened
          type: string
          example: https://en.wikipedia.org/wiki/Wikipedia
    ShortenResponse:
      type: object
      required:
      - short
      properties:
        short:
          description: Shortened link
          type: string
          example: wiki
