groups:
  - name: UrlShortenerAlerts
    interval: 30s
    rules:
      - alert: High traffic
        for: 5s
        expr: rate(http_requests_total[1m]) > 100
        labels:
          host: "{{ $labels.instance }}"
          severity: "warning"
        annotations:
          summary: "Unexpectedly high traffic"
          description: "RPS is higher than 100, that is unexpected for now"
