name: Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      working-directory: ./backend
      run: cargo fmt --check
    - name: Linter
      working-directory: ./backend
      run: cargo clippy
    - name: Build
      working-directory: ./backend
      run: cargo build --verbose
    - name: Unit tests
      working-directory: ./backend
      run: cargo test
